import { QlooParams } from "@/services/qloo/params/common";
import { FilterType } from "@/services/qloo/params/common/supporting-types.ts";

export type ExtractedParams = Pick<
  QlooParams,
  | "biasTrends"
  | "filterAddress"
  | "filterExcludeEntities"
  | "filterExcludeTags"
  | "operatorExcludeTags"
  | "filterExternalExists"
  | "operatorFilterExternalExists"
  | "filterExternalTripadvisorRatingCountMax"
  | "filterExternalTripadvisorRatingCountMin"
  | "filterExternalTripadvisorRatingMax"
  | "filterExternalTripadvisorRatingMin"
  | "filterGeocodeName"
  | "filterGeocodeAdmin1Region"
  | "filterGeocodeAdmin2Region"
  | "filterGeocodeCountryCode"
  | "filterHotelClassMax"
  | "filterHotelClassMin"
  | "filterHours"
  | "filterLocation"
  | "filterLocationGeohash"
  | "filterExcludeLocationGeohash"
  | "filterLocationRadius"
  | "filterParentsTypes"
  | "filterPopularityMin"
  | "filterPopularityMax"
  | "filterPriceLevelMin"
  | "filterPriceLevelMax"
  | "filterPriceRangeFrom"
  | "filterPriceRangeTo"
  | "filterPropertiesBusinessRatingMin"
  | "filterPropertiesBusinessRatingMax"
  | "filterExternalResyRatingMin"
  | "filterExternalResyRatingMax"
  | "filterExternalResyCountMin"
  | "filterExternalResyCountMax"
  | "filterExternalResyPartySizeMin"
  | "filterExternalResyPartySizeMax"
  | "filterReferencesBrand"
  | "filterResultsEntities"
  | "filterResultsEntitiesQuery"
  | "filterTags"
  | "operatorFilterTags"
  | "offset"
  | "signalDemographicsAge"
  | "signalDemographicsAudiences"
  | "signalDemographicsAudiencesWeight"
  | "signalDemographicsGender"
  | "signalInterestsEntities"
  | "signalInterestsTags"
  | "take"
>;

export interface PlaceParams extends ExtractedParams {
  filterType: FilterType.Place;
}
